In [1]:
import numpy as np

## NumPy second phase

### 1D Array Indexing and Slicing

In [2]:
oneD = np.array(range(10))

print("One dementional array",oneD)
print("Basic Slicing in One dementional array",oneD[4:9])
print("Basic Slicing with steps in OneD array",oneD[2:9:2])
print("Basic Slicing with negative in OneD array",oneD[2:-2])
print("Basic Slicing with negative in OneD array",oneD[-2])


One dementional array [0 1 2 3 4 5 6 7 8 9]
Basic Slicing in One dementional array [4 5 6 7 8]
Basic Slicing with steps in OneD array [2 4 6 8]
Basic Slicing with negative in OneD array [2 3 4 5 6 7]
Basic Slicing with negative in OneD array 8


### 2D Array Indexing and Slicing

In [ ]:
twoD = np.array([[1,2,3,4],
                 [3,5,6,7],
                 [8,9,10,11]])

print("Two dementional array",twoD)
print("TwoD array specific value",twoD[1,3])
print("TwoD array entire row ",twoD[2])
print("TwoD array entire colomn ",twoD[:,1])
print("TwoD array slicing: ", twoD[1, 2:4])

# Get columns 1 and 2 from all rows
print("TwoD array slicing: ",twoD[:, 1:3])


Two dementional array [[ 1  2  3  4]
 [ 3  5  6  7]
 [ 8  9 10 11]]
TwoD array specific value 7
TwoD array entire row  [ 8  9 10 11]
TwoD array entire colomn  [2 5 9]
TwoD array slicing:  [6 7]
TwoD array slicing:  [[ 2  3]
 [ 5  6]
 [ 9 10]]


### Sorting

In [10]:
oneD = np.array([100,212,203,102,9,30,304,103])

print("OneD Sorting: ",np.sort(oneD))

twoD = np.array([[1112,235,6433,43244],
                 [353,5432,2426,347],
                 [800,90,101,112]])

print("TwoD Sorting normal:",np.sort(twoD))

print("TwoD Sorting with Row: ",np.sort(twoD, axis=1))

print("TwoD Sorting with Colomn: ",np.sort(twoD, axis=0))


OneD Sorting:  [  9  30 100 102 103 203 212 304]
TwoD Sorting normal: [[  235  1112  6433 43244]
 [  347   353  2426  5432]
 [   90   101   112   800]]
TwoD Sorting with Row:  [[  235  1112  6433 43244]
 [  347   353  2426  5432]
 [   90   101   112   800]]
TwoD Sorting with Colomn:  [[  353    90   101   112]
 [  800   235  2426   347]
 [ 1112  5432  6433 43244]]


### Filter Simple way

In [12]:
oneD = np.array(range(100))

# Create an empty list
filter_arr = []

# go through each element in arr
for element in oneD:
  # if the element is completely divisble by 2, set the value to True, otherwise False
  if element % 2 == 0:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = oneD[filter_arr]

print(filter_arr)
print(newarr)


[True, False, True, False, True, False, True, False, True, False, True, False, True, False, True, False, True, False, True, False, True, False, True, False, True, False, True, False, True, False, True, False, True, False, True, False, True, False, True, False, True, False, True, False, True, False, True, False, True, False, True, False, True, False, True, False, True, False, True, False, True, False, True, False, True, False, True, False, True, False, True, False, True, False, True, False, True, False, True, False, True, False, True, False, True, False, True, False, True, False, True, False, True, False, True, False, True, False, True, False]
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]


## Filter Complex 

In [13]:
oneD = np.array(range(100))

evenNumber = oneD[oneD % 2 == 0]

print("Filter even number: ",evenNumber)

Filter even number:  [ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]
