In [2]:
# NumPy Array Creation Methods - Examples
import numpy as np

In [2]:
# 1. From Python Objects
arr1 = np.array([1, 2, 3])
print("From list:", arr1)
arr2 = np.array((4, 5, 6))
print("From tuple:", arr2)
arr3 = np.array([[1, 2], [3, 4]])
print("From nested lists:", arr3)

From list: [1 2 3]
From tuple: [4 5 6]
From nested lists: [[1 2]
 [3 4]]


In [3]:
# 2. Built-in Creation Functions
arr4 = np.zeros((2, 3))
print("Zeros:", arr4)
arr5 = np.ones((2, 3))
print("Ones:", arr5)
arr6 = np.full((2, 3), 7)
print("Full:", arr6)
arr7 = np.eye(3)
print("Identity matrix (eye):", arr7)
arr8 = np.identity(3)
print("Identity matrix (identity):", arr8)
arr9 = np.diag([10, 20, 30])
print("Diagonal matrix:", arr9)

Zeros: [[0. 0. 0.]
 [0. 0. 0.]]
Ones: [[1. 1. 1.]
 [1. 1. 1.]]
Full: [[7 7 7]
 [7 7 7]]
Identity matrix (eye): [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Identity matrix (identity): [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Diagonal matrix: [[10  0  0]
 [ 0 20  0]
 [ 0  0 30]]


In [3]:
# 3. Ranges and Sequences
arr10 = np.arange(0, 10, 2)
print("Arange:", arr10)
arr11 = np.linspace(0, 1, 5)
print("Linspace:", arr11)
arr12 = np.logspace(1, 3, 4)
print("Logspace:", arr12)

Arange: [0 2 4 6 8]
Linspace: [0.   0.25 0.5  0.75 1.  ]
Logspace: [  10.           46.41588834  215.443469   1000.        ]


In [4]:
# 4. Random Arrays
arr13 = np.random.rand(2, 3)
print("Random uniform (0–1):", arr13)
arr14 = np.random.randn(2, 3)
print("Random normal distribution:", arr14)
arr15 = np.random.randint(0, 10, (2, 3))
print("Random integers:", arr15)
arr16 = np.random.normal(loc=5.0, scale=2.0, size=(2, 3))
print("Random normal with mean 5, std 2:", arr16)

Random uniform (0–1): [[0.93085896 0.21260188 0.04264785]
 [0.84917742 0.59207201 0.73568711]]
Random normal distribution: [[-1.82591498  1.26756909  0.55493111]
 [ 1.5410602  -0.98187967 -0.54524288]]
Random integers: [[6 1 9]
 [4 4 6]]
Random normal with mean 5, std 2: [[7.45344044 9.81002116 7.88750874]
 [7.10229442 6.39469101 8.24117346]]


In [5]:
# 5. Empty or Uninitialized Arrays
arr17 = np.empty((2, 3))
print("Empty array (junk values):", arr17)

Empty array (junk values): [[7.45344044 9.81002116 7.88750874]
 [7.10229442 6.39469101 8.24117346]]


In [6]:
# 6. Structured or Special Patterns
arr18 = np.tile([1, 2], (2, 3))
print("Tile pattern:", arr18)
arr19 = np.repeat([1, 2], 3)
print("Repeat elements:", arr19)
x = np.array([1, 2, 3])
y = np.array([4, 5])
X, Y = np.meshgrid(x, y)
print("Meshgrid X:", X)
print("Meshgrid Y:", Y)

Tile pattern: [[1 2 1 2 1 2]
 [1 2 1 2 1 2]]
Repeat elements: [1 1 1 2 2 2]
Meshgrid X: [[1 2 3]
 [1 2 3]]
Meshgrid Y: [[4 4 4]
 [5 5 5]]


In [7]:
# 7. From Existing Arrays (Copy, Reshape, Cast)
a = np.array([1, 2, 3, 4, 5, 6])
arr20 = np.copy(a)
print("Copy of array:", arr20)
arr21 = a.reshape((2, 3))
print("Reshaped array:", arr21)
arr22 = a.astype(np.float32)
print("Changed data type:", arr22)

Copy of array: [1 2 3 4 5 6]
Reshaped array: [[1 2 3]
 [4 5 6]]
Changed data type: [1. 2. 3. 4. 5. 6.]
