In [1]:
import numpy as np
import time as time

### NumPy Array
## Creating 1d and 2d array using numpy

In [3]:
array_1d = np.array([1,2,3,4])
print("1D Array: ", array_1d)

array_2d = np.array([[1,2,3,4],[5,6,7,8]])
print("2D Array: ", array_2d)


1D Array:  [1 2 3 4]
2D Array:  [[1 2 3 4]
 [5 6 7 8]]


### NumPy Array Vs List


In [4]:
py_list = [1,2,3,4]
print("Python list multiplication: ", py_list * 2)

num_array = np.array([1,2,3,4])
print("Python array multiplication: ", num_array * 2)

Python list multiplication:  [1, 2, 3, 4, 1, 2, 3, 4]
Python array multiplication:  [2 4 6 8]


## NumPy Array Vs List time difference


In [5]:
start = time.time()

py_list = [i*2 for i in range(10000000)] * 2
# print("Python list multiplication: ", py_list * 2)
print("Python list operation time: ", time.time() - start)


start = time.time()

num_array = np.arange(10000000) * 2
# print("Python list multiplication: ", num_array * 2)
print("Python list operation time: ", time.time() - start)



Python list operation time:  0.81076979637146
Python list operation time:  0.03102731704711914


## Creating array from scratch in numpy


In [6]:
zeros = np.zeros((3,4))
print("numpy zeros \n",zeros)
arr5 = np.ones((2, 3))
print("Ones:", arr5)
arr6 = np.full((2, 3), 7)
print("Full:", arr6)
arr7 = np.eye(3)
print("Identity matrix (eye):", arr7)
arr8 = np.identity(3)
print("Identity matrix (identity):", arr8)

numpy zeros 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones: [[1. 1. 1.]
 [1. 1. 1.]]
Full: [[7 7 7]
 [7 7 7]]
Identity matrix (eye): [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Identity matrix (identity): [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Vector , Matrix and Tensor


In [5]:
vector = np.array([1,2,3,4])
print("Vectors: ",vector)

matrix = np.array([[1,2,3,4],[5,6,7,8]])
print("matrix: ",matrix)

tensor = np.array([[[1,2],[3,4]],
                   [[5,6],[7,8]]])
print("tensor: ",tensor)


Vectors:  [1 2 3 4]
matrix:  [[1 2 3 4]
 [5 6 7 8]]
tensor:  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Numpy Array Properties


In [ ]:
numpy_array = np.array([[1,2,3],[4,1,4]])

print("Size: ",numpy_array.size)
print("Dim: ",numpy_array.ndim)
print("Shape: ", numpy_array.shape)
print("Data Type: ",numpy_array.dtype)
print("Data: ", numpy_array.data)


Size:  6
Dim:  2
Shape:  (2, 3)
Data Type:  int64
Data:  <memory at 0x10627c930>


### Reshaping , Flatten , Ravel and Transpose

In [8]:
numpy_array = np.array([[1,2,3],[4,1,4]])

reshape = numpy_array.reshape((3,2))
print("Reshaped: ",reshape)

flattened = reshape.flatten() # Created a Copy 
print("Flattened: ",flattened)

raveled = numpy_array.ravel() # returns a view 
print("Raveled: ",raveled)

transposed = reshape.transpose()
print("Reshaped array Transposed: ",transposed)

transposed = numpy_array.transpose()
print("Main array Transposed: ",transposed)


Reshaped:  [[1 2]
 [3 4]
 [1 4]]
Flattened:  [1 2 3 4 1 4]
Raveled:  [1 2 3 4 1 4]
Reshaped array Transposed:  [[1 3 1]
 [2 4 4]]
Main array Transposed:  [[1 4]
 [2 1]
 [3 4]]
