In [2]:
import numpy as np
import time as time

### NumPy Array
## Creating 1d and 2d array using numpy

In [ ]:
array_1d = np.array([1,2,3,4])
print("1D Array: ", array_1d)

array_2d = np.array([[1,2,3,4],[5,6,7,8]])
print("2D Array: ", array_2d)


### NumPy Array Vs List


In [ ]:
py_list = [1,2,3,4]
print("Python list multiplication: ", py_list * 2)

num_array = np.array([1,2,3,4])
print("Python array multiplication: ", num_array * 2)

## NumPy Array Vs List time difference


In [2]:
start = time.time()

py_list = [i*2 for i in range(10000000)] * 2
# print("Python list multiplication: ", py_list * 2)
print("Python list operation time: ", time.time() - start)


start = time.time()

num_array = np.arange(10000000) * 2
# print("Python list multiplication: ", num_array * 2)
print("Python list operation time: ", time.time() - start)



Python list operation time:  0.7033278942108154
Python list operation time:  0.018496990203857422


## Creating array from scratch in numpy


In [3]:
zeros = np.zeros((3,4))
print("numpy zeros \n",zeros)
arr5 = np.ones((2, 3))
print("Ones:", arr5)
arr6 = np.full((2, 3), 7)
print("Full:", arr6)
arr7 = np.eye(3)
print("Identity matrix (eye):", arr7)
arr8 = np.identity(3)
print("Identity matrix (identity):", arr8)

numpy zeros 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones: [[1. 1. 1.]
 [1. 1. 1.]]
Full: [[7 7 7]
 [7 7 7]]
Identity matrix (eye): [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Identity matrix (identity): [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Vector , Matrix and Tensor


In [5]:
vector = np.array([1,2,3,4])
print("Vectors: ",vector)

matrix = np.array([[1,2,3,4],[5,6,7,8]])
print("matrix: ",matrix)

tensor = np.array([[[1,2],[3,4]],
                   [[5,6],[7,8]]])
print("tensor: ",tensor)


Vectors:  [1 2 3 4]
matrix:  [[1 2 3 4]
 [5 6 7 8]]
tensor:  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
